name: Builds Meilisearch Docker image via the traditional method

on:
  push:
    branches: [ "stable" ]

permissions:
  packages: write

jobs:
  nix-build:
    name: Builds Docker image via nix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Build the image
        run: docker build -t meilisearch-traditional:latest .

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Push to Container registry
        run: |
          docker tag meilisearch-traditional:latest ghcr.io/${{ github.repository_owner }}/meilisearch-traditional:latest
          docker push --all-tags ghcr.io/${{ github.repository_owner }}/meilisearch-traditional
